basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handler.StatusResponse:
    properties:
      status:
        type: string
    type: object
  repository.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: API for managing users
  title: Try 12 Go API
  version: "1.0"
paths:
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.StatusResponse'
      summary: Health status
      tags:
      - health
  /users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repository.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: List users
      tags:
      - users
swagger: "2.0"
